name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build the Blazor WebAssembly app
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release -o ./dist

      - name: Disable Jekyll (important to avoid conflicts)
        run: touch ./dist/.nojekyll

      - name: List dist contents
        run: ls -R ./dist  # To verify the correct files are in the dist folder

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to (make sure your GitHub Pages source is set to this branch)
          folder: ./dist    # The folder where the built website is located
          token: ${{ secrets.PERSONAL_TOKEN }}  # GitHub's token for authentication
